name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^1.0.3
  get: ^4.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true